POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

POST http://localhost:3000/login/
Content-Type:application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

GET http://localhost:3000/user/tweets/feed/

###

GET http://localhost:3000/user/following/

###


GET http://localhost:3000/user/followers/

###

GET http://localhost:3000/tweets/:tweetId/

###

GET http://localhost:3000/tweets/:tweetId/likes/

###

GET http://localhost:3000/tweets/:tweetId/replies/

###

GET http://localhost:3000/user/tweets/

###

POST http://localhost:3000/user/tweets/
Content-Type:application/json

###

DELETE http://localhost:3000/tweets/:tweetId/

###